name: Run Tests on Push

on:
  push:
    branches:
      - main

jobs:
  execute-tests-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test command
        working-directory: ./tests
        run: |
          echo "currently in $(pwd)"
          python3 -m unittest

  execute-tests-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses:  action/checkout@v4

      - name: Run test command
        working-directory: ./tests
        run: |
          python -m unittest
    
      
